version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tarea1
    command: python manage.py runserver 0:8081
    volumes:
      - .:/ribbit
    ports:
      - "8081:8081"
